name: SULSUL API Webserver & Batch workflow deploy


on:
  push:
    branches:
      - main


jobs:

  deploy-eb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS ElasticBeanstalk CLI
        run: |
          sudo apt-get install python3-pip
          pip3 install awsebcli

      - name: Install & Setup AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-northeast-2

      - name: Deploy AWS ElasticBeanstalk
        run: |
          eb init -r ap-northeast-2 -p Python sulsul
          eb deploy -l "GitHubActions-$(date +%s)" Sulsul-env-1


  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install & Setup AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID_LAMBDA }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_LAMBDA }}
          aws configure set region ap-northeast-2

      # - name: Deploy Ranking batch workflow to AWS Lambda
      #   run: |
      #     cp -R core/ batch/ranking/core/ && cd batch/ranking
      #     zip -r ranking.zip . && cd ../../
      #     aws lambda update-function-code \
      #       --function-name ranking \
      #       --region ap-northeast-2 \
      #       --zip-file fileb://batch/ranking/ranking.zip \
      #       --publish
          
      - name: Deploy Search volume batch workflow to AWS Lambda
        run: |
          cp -R core/ batch/search-volume/core/ && cd batch/search-volume
          zip -r search-volume.zip . && cd ../../
          aws lambda update-function-code \
            --function-name search-volume \
            --region ap-northeast-2 \
            --zip-file fileb://batch/search-volume/search-volume.zip \
            --publish

  deploy-lambda-rangking-batch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_LAMBDA }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_LAMBDA }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker buildx build -f ./batch/ranking/Dockerfile -t 998164501102.dkr.ecr.ap-northeast-2.amazonaws.com/sulsul-ranking-batch:latest --push .
          aws lambda update-function-code --function-name ranking --image-uri 998164501102.dkr.ecr.ap-northeast-2.amazonaws.com/sulsul-ranking-batch:latest